In [1]:
# Importing our libraries/modules:
import pandas as pd
import scipy
import matplotlib.pyplot as plt
import numpy as np
import os
import requests

In [2]:
# Reading our dataset 'census_2015.csv' printing a preview:
census_2015 = pd.read_csv('../Resources/census_2015.csv')
census_2015.head()

,CensusId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga,55221,26745,28476,2.6,75.8,18.5,0.4,...,0.5,1.3,1.8,26.5,23986,73.6,20.9,5.5,0.0,7.6
1,1003,Alabama,Baldwin,195121,95314,99807,4.5,83.1,9.5,0.6,...,1.0,1.4,3.9,26.4,85953,81.5,12.3,5.8,0.4,7.5
2,1005,Alabama,Barbour,26932,14497,12435,4.6,46.2,46.7,0.2,...,1.8,1.5,1.6,24.1,8597,71.8,20.8,7.3,0.1,17.6
3,1007,Alabama,Bibb,22604,12073,10531,2.2,74.5,21.4,0.4,...,0.6,1.5,0.7,28.8,8294,76.8,16.1,6.7,0.4,8.3
4,1009,Alabama,Blount,57710,28512,29198,8.6,87.9,1.5,0.3,...,0.9,0.4,2.3,34.9,22189,82.0,13.5,4.2,0.4,7.7

In [3]:
# Filling in the rows with no values/blanks and placing to 0 so we can run calculations:
census_2015.ChildPoverty.fillna(value=0, inplace=True)
census_2015.Income.fillna(value=0, inplace=True)
census_2015.IncomeErr.fillna(value=0, inplace=True)
census_2015

,CensusId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga,55221,26745,28476,2.6,75.8,18.5,0.4,...,0.5,1.3,1.8,26.5,23986,73.6,20.9,5.5,0.0,7.6
1,1003,Alabama,Baldwin,195121,95314,99807,4.5,83.1,9.5,0.6,...,1.0,1.4,3.9,26.4,85953,81.5,12.3,5.8,0.4,7.5
2,1005,Alabama,Barbour,26932,14497,12435,4.6,46.2,46.7,0.2,...,1.8,1.5,1.6,24.1,8597,71.8,20.8,7.3,0.1,17.6
3,1007,Alabama,Bibb,22604,12073,10531,2.2,74.5,21.4,0.4,...,0.6,1.5,0.7,28.8,8294,76.8,16.1,6.7,0.4,8.3
4,1009,Alabama,Blount,57710,28512,29198,8.6,87.9,1.5,0.3,...,0.9,0.4,2.3,34.9,22189,82.0,13.5,4.2,0.4,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,72145,Puerto Rico,Vega Baja,56858,27379,29479,96.4,3.4,0.1,0.0,...,1.2,1.3,0.3,32.0,13660,78.3,17.6,4.1,0.0,15.2
3216,72147,Puerto Rico,Vieques,9130,4585,4545,96.7,2.9,0.0,0.0,...,10.8,0.0,1.4,14.0,2860,44.5,41.6,13.6,0.3,12.2
3217,72149,Puerto Rico,Villalba,24685,12086,12599,99.7,0.0,0.0,0.0,...,3.2,0.0,3.3,26.9,6795,59.2,27.5,13.1,0.2,25.9
3218,72151,Puerto Rico,Yabucoa,36279,17648,18631,99.8,0.2,0.0,0.0,...,2.3,2.3,1.5,29.5,8083,65.1,27.6,7.3,0.0,24.3
3219,72153,Puerto Rico,Yauco,39474,19047,20427,99.5,0.5,0.0,0.0,...,1.6,0.7,3.1,24.6,8923,68.0,27.6,4.4,0.0,27.1

In [4]:
# Performing calculaions...and building a new dataframe by 'county' across the entire country:
total_pop_county = census_2015["TotalPop"]
men_county = census_2015["Men"]
women_county = census_2015["Women"]
citizen_county = census_2015["Citizen"]
income_county = census_2015["Income"]
income_err_county = census_2015["IncomeErr"]
income_per_capita_county = census_2015["IncomePerCap"]
income_per_cap_err_county = census_2015["IncomePerCapErr"]
mean_commute_county = census_2015["MeanCommute"]
employed_county = census_2015["Employed"]

hispanic_county = census_2015["Hispanic"] * census_2015["TotalPop"] / 100
white_county = census_2015["White"] * census_2015["TotalPop"] / 100
black_county = census_2015["Black"] * census_2015["TotalPop"] / 100
native_county = census_2015["Native"] * census_2015["TotalPop"] / 100
asian_county = census_2015["Asian"] * census_2015["TotalPop"] / 100
pacific_county = census_2015["Pacific"] * census_2015["TotalPop"] / 100

professional_county = census_2015["Professional"] * census_2015["Employed"] / 100
service_county = census_2015["Service"] * census_2015["Employed"] / 100
office_county = census_2015["Office"] * census_2015["Employed"] / 100
construction_county = census_2015["Construction"] * census_2015["Employed"] / 100
production_county = census_2015["Production"] * census_2015["Employed"] / 100

drive_county = census_2015["Drive"] * census_2015["Employed"] / 100
carpool_county = census_2015["Carpool"] * census_2015["Employed"] / 100
transit_county = census_2015["Transit"] * census_2015["Employed"] / 100
walk_county = census_2015["Walk"] * census_2015["Employed"] / 100
othertrans_county = census_2015["OtherTransp"] * census_2015["Employed"] / 100
workathome_county = census_2015["WorkAtHome"] * census_2015["Employed"] / 100

privatework_county = census_2015["PrivateWork"] * census_2015["Employed"] / 100
publicwork_county = census_2015["PublicWork"] * census_2015["Employed"] / 100
self_employed_county = census_2015["SelfEmployed"] * census_2015["Employed"] / 100
familywork_county = census_2015["FamilyWork"] * census_2015["Employed"] / 100

poverty_county = census_2015["Poverty"] * census_2015["TotalPop"] / 100
child_poverty_county = census_2015["ChildPoverty"] * census_2015["TotalPop"] / 100

unemployment_county = census_2015["Unemployment"] * census_2015["TotalPop"] / 100

all_county = pd.DataFrame ({
                                "State": census_2015["State"],
                                "County": census_2015["County"],
                                "TotalPop": total_pop_county,
                                "Men": men_county,
                                "Women": women_county,
                                "Hispanic": hispanic_county,
                                "White": white_county,
                                "Black": black_county,
                                "Native": native_county,
                                "Asian": asian_county,
                                "Pacific": pacific_county,
                                "VotingAgeCitizen": citizen_county,
                                "Income": income_county,
                                "IncomeErr": income_err_county,
                                "IncomePerCap": income_per_capita_county,
                                "IncomePerCapErr": income_per_cap_err_county,
                                "Employed": employed_county,
                                "Professional": professional_county,
                                "Service": service_county,
                                "Office": office_county,
                                "Construction": construction_county,
                                "Production": production_county,
                                "Drive": drive_county,
                                "Carpool": carpool_county,
                                "Transit": transit_county,
                                "Walk": walk_county,
                                "OtherTrans": othertrans_county,
                                "WorkatHome": workathome_county,
                                "MeanCommute": mean_commute_county,
                                "PrivateWork": privatework_county,
                                "PublicWork": publicwork_county,
                                "SelfEmployed": self_employed_county,
                                "FamilyWork": familywork_county,
                                "Poverty": poverty_county,
                                "ChildPoverty": child_poverty_county,
                                "Unemployment": unemployment_county})

# Formatting to export:
all_county['Hispanic'] = all_county['Hispanic'].astype(int)
all_county['White'] = all_county['White'].astype(int)
all_county['Black'] = all_county['Black'].astype(int)
all_county['Asian'] = all_county['Asian'].astype(int)
all_county['Native'] = all_county['Native'].astype(int)
all_county['Pacific'] = all_county['Pacific'].astype(int)
all_county['Poverty'] = all_county['Poverty'].astype(int)
all_county['ChildPoverty'] = all_county['ChildPoverty'].astype(int)
all_county['Professional'] = all_county['Professional'].astype(int)
all_county['Service'] = all_county['Service'].astype(int)
all_county['Office'] = all_county['Office'].astype(int)
all_county['Construction'] = all_county['Construction'].astype(int)
all_county['Production'] = all_county['Production'].astype(int)
all_county['Drive'] = all_county['Drive'].astype(int)
all_county['Carpool'] = all_county['Carpool'].astype(int)
all_county['Transit'] = all_county['Transit'].astype(int)
all_county['Walk'] = all_county['Walk'].astype(int)
all_county['OtherTrans'] = all_county['OtherTrans'].astype(int)
all_county['Walk'] = all_county['Walk'].astype(int)
all_county['WorkatHome'] = all_county['WorkatHome'].astype(int)
all_county['MeanCommute'] = all_county['MeanCommute'].astype(int)
all_county['PrivateWork'] = all_county['PrivateWork'].astype(int)
all_county['PublicWork'] = all_county['PublicWork'].astype(int)
all_county['SelfEmployed'] = all_county['SelfEmployed'].astype(int)
all_county['FamilyWork'] = all_county['FamilyWork'].astype(int)
all_county['Income'] = all_county['Income'].astype(int)
all_county['IncomeErr'] = all_county['IncomeErr'].astype(int)
all_county['IncomePerCap'] = all_county['IncomePerCap'].astype(int)
all_county['IncomePerCapErr'] = all_county['IncomePerCapErr'].astype(int)
all_county['Unemployment'] = all_county['Unemployment'].astype(int)
all_county

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,...,OtherTrans,WorkatHome,MeanCommute,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Poverty,ChildPoverty,Unemployment
0,Alabama,Autauga,55221,26745,28476,1435,41857,10215,220,552,...,311,431,26,17653,5013,1319,0,7123,10271,4196
1,Alabama,Baldwin,195121,95314,99807,8780,162145,18536,1170,1365,...,1203,3352,26,70051,10572,4985,343,26146,37463,14634
2,Alabama,Barbour,26932,14497,12435,1238,12442,12577,53,107,...,128,137,24,6172,1788,627,8,7190,12200,4740
3,Alabama,Bibb,22604,12073,10531,497,16839,4837,90,22,...,124,58,28,6369,1335,555,33,3797,6306,1876
4,Alabama,Blount,57710,28512,29198,4963,50727,865,173,57,...,88,510,34,18194,2995,931,88,9637,15697,4443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,Puerto Rico,Vega Baja,56858,27379,29479,54811,1933,56,0,0,...,177,40,32,10695,2404,560,0,27576,31897,8642
3216,Puerto Rico,Vieques,9130,4585,4545,8828,264,0,0,0,...,0,40,14,1272,1189,388,8,3569,5304,1113
3217,Puerto Rico,Villalba,24685,12086,12599,24610,0,0,0,0,...,0,224,26,4022,1868,890,13,13329,16859,6393
3218,Puerto Rico,Yabucoa,36279,17648,18631,36206,72,0,0,36,...,185,121,29,5262,2230,590,0,18973,22529,8815
3219,Puerto Rico,Yauco,39474,19047,20427,39276,197,0,0,0,...,62,276,24,6067,2462,392,0,20408,22223,10697

In [5]:
# Creating/exporting output file for 2015 'county':
all_county.to_csv('../Output/2015_cleaned_all_county.csv')

In [6]:
# Now we can take a step further in the data cleaning process by grouping by 'state':
total_pop_state = all_county.groupby(["State"]).sum()["TotalPop"]
men_state = all_county.groupby(["State"]).sum()["Men"]
women_state = all_county.groupby(["State"]).sum()["Women"]
citizen_state = all_county.groupby(["State"]).sum()["VotingAgeCitizen"]
income_state = all_county.groupby(["State"]).mean()["Income"]
income_err_state = all_county.groupby(["State"]).mean()["IncomeErr"]
income_per_capita_state = all_county.groupby(["State"]).mean()["IncomePerCap"]
income_per_cap_err_state = all_county.groupby(["State"]).mean()["IncomePerCapErr"]
mean_commute_state = all_county.groupby(["State"]).mean()["MeanCommute"]
employed_state = all_county.groupby(["State"]).sum()["Employed"]

state_hispanic = all_county.groupby(["State"]).sum()["Hispanic"].round()
state_white = all_county.groupby(["State"]).sum()["White"].round()
state_black = all_county.groupby(["State"]).sum()["Black"].round()
state_native = all_county.groupby(["State"]).sum()["Native"].round()
state_asian = all_county.groupby(["State"]).sum()["Asian"].round()
state_pacific = all_county.groupby(["State"]).sum()["Pacific"].round()

professional_state = all_county.groupby(["State"]).sum()["Professional"].round()
service_state = all_county.groupby(["State"]).sum()["Service"].round()
office_state = all_county.groupby(["State"]).sum()["Office"].round()
construction_state = all_county.groupby(["State"]).sum()["Construction"].round()
production_state = all_county.groupby(["State"]).sum()["Production"].round()

drive_state = all_county.groupby(["State"]).sum()["Drive"].round()
carpool_state = all_county.groupby(["State"]).sum()["Carpool"].round()
transit_state = all_county.groupby(["State"]).sum()["Transit"].round()
walk_state = all_county.groupby(["State"]).sum()["Walk"].round()
othertrans_state = all_county.groupby(["State"]).sum()["OtherTrans"].round()
workathome_state = all_county.groupby(["State"]).sum()["WorkatHome"].round()

privatework_state = all_county.groupby(["State"]).sum()["PrivateWork"].round()
publicwork_state = all_county.groupby(["State"]).sum()["PublicWork"].round()
self_employed_state = all_county.groupby(["State"]).sum()["SelfEmployed"].round()
familywork_state = all_county.groupby(["State"]).sum()["FamilyWork"].round()

poverty_state = all_county.groupby(["State"]).sum()["Poverty"].round()
child_poverty_state = all_county.groupby(["State"]).sum()["ChildPoverty"].round()

unemployment_state = all_county.groupby(["State"]).sum()["Unemployment"].round()

all_race_state = pd.DataFrame({
                                "TotalPop": total_pop_state,
                                "Men": men_state,
                                "Women": women_state,
                                "Hispanic": state_hispanic,
                                "White": state_white,
                                "Black": state_black,
                                "Native": state_native,
                                "Asian": state_asian,
                                "Pacific": state_pacific,
                                "VotingAgeCitizen": citizen_state,
                                "Income": income_state,
                                "IncomeErr": income_err_state,
                                "IncomePerCap": income_per_capita_state,
                                "IncomePerCapErr": income_per_cap_err_state,
                                "Employed": employed_state,
                                "Professional": professional_state,
                                "Service": service_state,
                                "Office": office_state,
                                "Construction": construction_state,
                                "Production": production_state,
                                "Drive": drive_state,
                                "Carpool": carpool_state,
                                "Transit": transit_state,
                                "Walk": walk_state,
                                "OtherTrans": othertrans_state,
                                "WorkatHome": workathome_state,
                                "MeanCommute": mean_commute_state,
                                "PrivateWork": privatework_state,
                                "PublicWork": publicwork_state,
                                "SelfEmployed": self_employed_state,
                                "FamilyWork": familywork_state,
                                "Poverty": poverty_state,
                                "ChildPoverty": child_poverty_state,
                                "Unemployment": unemployment_state})

# Formatting to export:
all_race_state['Hispanic'] = all_race_state['Hispanic'].astype(int)
all_race_state['White'] = all_race_state['White'].astype(int)
all_race_state['Black'] = all_race_state['Black'].astype(int)
all_race_state['Asian'] = all_race_state['Asian'].astype(int)
all_race_state['Native'] = all_race_state['Native'].astype(int)
all_race_state['Pacific'] = all_race_state['Pacific'].astype(int)
all_race_state['Poverty'] = all_race_state['Poverty'].astype(int)
all_race_state['ChildPoverty'] = all_race_state['ChildPoverty'].astype(int)
all_race_state['Professional'] = all_race_state['Professional'].astype(int)
all_race_state['Service'] = all_race_state['Service'].astype(int)
all_race_state['Office'] = all_race_state['Office'].astype(int)
all_race_state['Construction'] = all_race_state['Construction'].astype(int)
all_race_state['Production'] = all_race_state['Production'].astype(int)
all_race_state['Drive'] = all_race_state['Drive'].astype(int)
all_race_state['Carpool'] = all_race_state['Carpool'].astype(int)
all_race_state['Transit'] = all_race_state['Transit'].astype(int)
all_race_state['Walk'] = all_race_state['Walk'].astype(int)
all_race_state['OtherTrans'] = all_race_state['OtherTrans'].astype(int)
all_race_state['Walk'] = all_race_state['Walk'].astype(int)
all_race_state['WorkatHome'] = all_race_state['WorkatHome'].astype(int)
all_race_state['MeanCommute'] = all_race_state['MeanCommute'].astype(int)
all_race_state['PrivateWork'] = all_race_state['PrivateWork'].astype(int)
all_race_state['PublicWork'] = all_race_state['PublicWork'].astype(int)
all_race_state['SelfEmployed'] = all_race_state['SelfEmployed'].astype(int)
all_race_state['FamilyWork'] = all_race_state['FamilyWork'].astype(int)
all_race_state['Income'] = all_race_state['Income'].astype(int)
all_race_state['IncomeErr'] = all_race_state['IncomeErr'].astype(int)
all_race_state['IncomePerCap'] = all_race_state['IncomePerCap'].astype(int)
all_race_state['IncomePerCapErr'] = all_race_state['IncomePerCapErr'].astype(int)
all_race_state['Unemployment'] = all_race_state['Unemployment'].astype(int)
all_race_state

,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,VotingAgeCitizen,...,OtherTrans,WorkatHome,MeanCommute,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Poverty,ChildPoverty,Unemployment
State,,,,,,,,,,,,,,,,,,,,,
Alabama,4830620,2341093,2489527,193159,3204658,1270556,22007,59324,1089,3620994,...,20994,56260,25,1583312,329430,105863,3715,910480,1318475,454437
Alaska,733375,384160,349215,47860,457438,23611,98381,42323,8638,523946,...,19750,16083,10,240061,88175,22190,634,74612,99617,61930
Arizona,6641928,3299088,3342840,2015055,3751927,263011,265835,193799,11587,4526594,...,77252,156279,21,2230882,412325,166404,5502,1210351,1724490,603924
Arkansas,2958208,1451913,1506295,203216,2177095,456609,16531,39968,6628,2164083,...,15580,40259,22,969630,205337,78614,2406,571519,821223,231142
California,38421464,19087135,19334329,14746502,14878698,2157932,144676,5192680,133245,24280349,...,437377,917120,24,13403787,2381720,1434085,34099,6260461,8451647,3845611
Colorado,5278906,2648667,2630239,1112543,3645866,202886,28865,150827,6085,3750953,...,63257,175819,20,2086203,365801,167714,5037,671100,887054,371187
Connecticut,3593222,1751607,1841615,527252,2487569,347023,4140,149292,0,2574178,...,20728,78074,25,1429343,235296,112637,2991,377780,513921,316990
Delaware,926454,448413,478041,80656,591724,195085,2737,33321,0,681606,...,4878,18130,25,353077,63124,17027,583,111662,162815,71495
District of Columbia,647484,306674,340810,66043,230504,310792,1294,23309,0,485116,...,17566,16890,29,236470,85805,14863,337,116547,172878,62158
Florida,19645772,9600009,10045763,4662105,11013296,3033792,41284,499715,7700,13933052,...,189642,435993,25,6957820,1067082,503058,12947,3254111,4730159,1912521
Georgia,10006693,4883331,5123362,914486,5460321,3054190,18694,358309,2389,6978660,...,69272,212440,24,3472207,666033,241594,7422,1848836,2637720,970109
Hawaii,1406299,709871,696428,138597,322407,27135,1857,516779,127706,1001729,...,23086,30227,21,471804,134533,45177,1224,157965,213883,85485
Idaho,1616547,810464,806083,191363,1342431,9320,17448,20769,1899,1130550,...,16839,42431,20,546102,113154,54715,1931,250122,307326,116862
Illinois,12873761,6316899,6556862,2120740,8043091,1821146,14594,640208,285,8979999,...,100871,256177,23,5037492,756997,284045,8370,1849183,2644706,1167270
Indiana,6568645,3235263,3333382,421038,5288445,594073,12036,120748,1230,4801113,...,44239,101308,23,2559413,334074,140438,4649,1012175,1448795,517062
Iowa,3093526,1534595,1558931,167929,2703776,95515,8445,62619,1727,2285126,...,24078,70405,18,1254487,213153,102312,3400,387492,488516,153207
Kansas,2892987,1439862,1453125,323197,2228816,163730,20429,74582,1031,2053919,...,18418,57361,17,1090690,222371,85400,2608,394117,515652,172979
Kentucky,4397353,2164208,2233145,143853,3761926,342165,7172,54690,1680,3297108,...,23983,58945,24,1499268,286193,102647,2957,831972,1155041,380261
Louisiana,4625253,2261156,2364097,218793,2750784,1474388,24912,77304,1092,3410634,...,41278,49570,26,1589480,312710,111087,2594,916437,1306060,379238
Maine,1329100,650081,679019,19470,1247579,14577,7508,14619,30,1048274,...,10598,35258,22,499949,91290,56693,963,185317,246999,91811
Maryland,5930538,2872643,3057895,533564,3144704,1723679,11226,354324,1109,4182241,...,37101,125789,29,2167820,663202,141861,3696,594311,808746,443822
Massachusetts,6705586,3249650,3455936,707169,4981389,434230,8670,399785,552,4850598,...,59452,155745,24,2780637,424503,206933,4306,778481,1031917,510891
Michigan,9900571,4861973,5038598,465586,7512805,1366241,47720,268943,577,7380136,...,56341,159322,22,3659940,486222,220313,7173,1655675,2316049,990787
Minnesota,5419171,2692166,2727005,270331,4427687,294017,51731,239227,556,3950807,...,46759,147225,20,2327030,336102,159277,4298,612737,798928,304036
Mississippi,2988081,1451723,1536358,86572,1714417,1112512,11997,28616,184,2210424,...,17595,26588,25,913680,222777,65646,1658,675977,950259,313966
Missouri,6045448,2964003,3081445,233394,4850300,691673,22462,105821,5068,4525035,...,35761,118710,23,2284927,357610,159642,5226,947444,1324976,455668
Montana,1014699,510163,504536,33640,882607,4558,63440,6800,752,781250,...,12003,30275,17,350657,87842,44444,2339,154229,194582,64295
Nebraska,1869365,929606,939759,186100,1509820,85511,12918,37602,955,1333860,...,12914,42475,17,763796,136799,65156,1837,238277,318710,87791
Nevada,2798636,1407735,1390901,769956,1455056,225577,24201,210721,17641,1863799,...,27306,41490,22,1046115,156402,64300,1375,432724,621046,293727
New Hampshire,1324201,653484,670717,42399,1210604,15686,2145,31026,89,1020130,...,8662,42085,24,555075,94291,48690,747,118211,158833,76162
New Jersey,8904413,4343027,4561386,1688178,5093771,1131762,8441,800991,252,6053893,...,79834,172193,29,3480774,593056,202379,5794,964839,1377386,786136
New Mexico,2084117,1032414,1051703,986896,817205,37637,177003,27068,999,1457632,...,17800,41044,19,621466,193899,58437,1745,438533,608767,194116
New York,19673174,9541801,10131373,3617603,11169037,2831128,44097,1558371,986,13531404,...,175538,362388,24,7253289,1444775,546106,11432,3084011,4324159,1631458
North Carolina,9845333,4795408,5049925,869561,6324182,2084916,108417,242391,4259,7107998,...,57788,204909,24,3461237,652446,252891,7194,1712933,2453678,937711
North Dakota,721640,367963,353677,20504,628120,11634,37596,8725,254,546486,...,4589,19504,17,291445,63548,31524,1157,82741,93389,21010
Ohio,11575977,5662893,5913084,390546,9291013,1393749,16957,215433,990,8709050,...,60310,189337,23,4418761,672901,267339,7492,1827006,2665605,948595
Oklahoma,3849733,1906944,1942789,372058,2591121,273936,267127,72954,4914,2768561,...,23713,59469,21,1316723,291424,107445,3778,643952,892771,246197
Oregon,3939233,1948453,1990780,486217,3042980,69292,36357,154660,14357,2867670,...,62503,112559,19,1395458,252410,138975,2778,650377,858211,371455
Pennsylvania,12779559,6245344,6534215,815207,9979028,1347695,15121,389489,344,9710416,...,82600,239653,24,5035025,649482,308795,8607,1724212,2462578,1018460
Puerto Rico,3583073,1713860,1869213,3547246,24831,2654,4,2648,18,2726223,...,21151,22786,28,721261,243577,96887,1729,1631029,2055236,657401
Rhode Island,1053661,510388,543273,143598,785470,56450,3861,33642,630,776565,...,7735,17938,23,426692,65733,25472,590,149948,211015,90554
South Carolina,4777576,2322409,2455167,254472,3051068,1304130,14033,66459,2556,3566508,...,33238,73606,25,1634236,327594,110395,3100,856925,1259872,458496
South Dakota,843190,423477,419713,27898,701636,12699,69892,10180,292,621770,...,6462,23987,16,327422,66667,35556,1131,119191,149081,40546
Tennessee,6499615,3167756,3331859,320206,4856845,1084285,13999,101691,2379,4828366,...,34841,104665,25,2281151,405128,197918,4474,1148312,1674768,555725
Texas,26538614,13171316,13367298,10194717,11636181,3073714,68207,1108335,19526,16864962,...,208925,496684,21,9602271,1673138,799113,17558,4586120,6486361,1879261
Utah,2903379,1459229,1444150,389486,2307610,29337,27064,62878,25677,1868008,...,26439,68330,19,1070395,204272,60790,1977,358445,421632,168013
Vermont,626604,308573,318031,10695,586528,6702,1947,8649,135,493124,...,5251,21776,23,248074,47671,30237,718,72234,94500,34487
Virginia,8256630,4060948,4195682,709314,5237825,1560908,16644,488848,5562,5948625,...,62333,182865,26,2970487,815683,199017,4623,962630,1322080,544584
Washington,6985464,3487725,3497739,836241,4943242,243256,81542,530708,42361,4937212,...,69527,178848,22,2530615,527312,195935,6021,927920,1203265,554525
West Virginia,1851420,913631,937789,25309,1713369,60411,2568,13293,361,1455848,...,7933,21930,27,574140,142824,33299,806,333578,463520,145717
Wisconsin,5742117,2851385,2890732,364462,4730133,354056,46129,143402,407,4294321,...,48999,117771,21,2372410,357136,148212,5092,744644,1009706,364960
Wyoming,579679,295561,284118,55762,489672,5929,11024,5167,402,430026,...,6335,13085,19,212611,61881,18714,684,66992,85434,28254

In [7]:
# Creating/exporting output file for 2015 'state':
all_race_state.to_csv('../Output/2015_cleaned_state.csv')