In [1]:
# Importing our libraries/modules:
import pandas as pd
import scipy
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Reading our cleaned dataset '2015' and printing for preview:
states_2015 = pd.read_csv('../Output/2015_cleaned_state.csv')
states_2015.head()

,State,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,...,OtherTrans,WorkatHome,MeanCommute,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Poverty,ChildPoverty,Unemployment
0,Alabama,4830620,2341093,2489527,193159,3204658,1270556,22007,59324,1089,...,20994,56260,25,1583312,329430,105863,3715,910480,1318475,454437
1,Alaska,733375,384160,349215,47860,457438,23611,98381,42323,8638,...,19750,16083,10,240061,88175,22190,634,74612,99617,61930
2,Arizona,6641928,3299088,3342840,2015055,3751927,263011,265835,193799,11587,...,77252,156279,21,2230882,412325,166404,5502,1210351,1724490,603924
3,Arkansas,2958208,1451913,1506295,203216,2177095,456609,16531,39968,6628,...,15580,40259,22,969630,205337,78614,2406,571519,821223,231142
4,California,38421464,19087135,19334329,14746502,14878698,2157932,144676,5192680,133245,...,437377,917120,24,13403787,2381720,1434085,34099,6260461,8451647,3845611

In [3]:
# Building a new dataframe to pull from and then be able to perform a summary of statistics:
sss_2015 = states_2015[['State', 'TotalPop', 'Men', 'Women', 'VotingAgeCitizen', 'MeanCommute', 'Income','Poverty', 'Unemployment']]
sss_2015.head()

,State,TotalPop,Men,Women,VotingAgeCitizen,MeanCommute,Income,Poverty,Unemployment
0,Alabama,4830620,2341093,2489527,3620994,25,37973,910480,454437
1,Alaska,733375,384160,349215,523946,10,64197,74612,61930
2,Arizona,6641928,3299088,3342840,4526594,21,43252,1210351,603924
3,Arkansas,2958208,1451913,1506295,2164083,22,36626,571519,231142
4,California,38421464,19087135,19334329,24280349,24,56013,6260461,3845611

In [4]:
# Performing calculations to pull stats:

# Calculating percentages (%) of men + women per state population:
tot_state_pop_2015 = sss_2015['TotalPop']
men_per_state_2015 = sss_2015['Men']
women_per_state_2015 = sss_2015['Women']
pct_men_2015 = (men_per_state_2015 / tot_state_pop_2015) * 100
pct_women_2015 = (women_per_state_2015 / tot_state_pop_2015) * 100

# Calculating percentage (%) of voting age citizens per state:
vot_age_2015 = sss_2015['VotingAgeCitizen']
pct_AdultsOver18_2015 = (vot_age_2015 / tot_state_pop_2015) * 100

# 'MeanCommute' will be renamed 'Average Commute Times (mins)'
# 'Income' will be renamed 'Average Income ($)'
# 'Poverty' will be renamed 'Poverty Rate (%)':
poverty_2015 = sss_2015['Poverty']
pct_pov_2015 = (poverty_2015 / tot_state_pop_2015) * 100

# Calculating percentage (%) of unemployment per state:
unemp_2015 = sss_2015['Unemployment']
pct_unemp_2015 = (unemp_2015 / tot_state_pop_2015) * 100

In [5]:
# States Summary of Statistics Table:

states_2015_stats = pd.DataFrame({
    "State": sss_2015['State'],
    "State Pop": tot_state_pop_2015,
    "Male Pop (%)": pct_men_2015,
    "Female Pop (%)": pct_women_2015,
    "Adult Pop (%)": pct_AdultsOver18_2015,
    "Avg Commute (min)": sss_2015['MeanCommute'],
    "Avg Income": sss_2015['Income'],
    "Poverty Rate (%)": pct_pov_2015,
    "Unemployed (%)": pct_unemp_2015
})
states_2015_stats.style.format({
    "State Pop": "{:,}",
    "Male Pop (%)": "{:.2f}",
    "Female Pop (%)": "{:.2f}",
    "Adult Pop (%)": "{:.2f}",
    "Avg Commute (min)": "{:.1f}",
    "Avg Income": "${:,}",
    "Poverty Rate (%)": "{:.2f}",
    "Unemployed (%)": "{:.2f}"
})

In [6]:
# Top States by 'Avg Income':
top_income_2015 = states_2015_stats.sort_values('Avg Income', ascending=False)
top_income_2015.head(5)

,State,State Pop,Male Pop (%),Female Pop (%),Adult Pop (%),Avg Commute (min),Avg Income,Poverty Rate (%),Unemployed (%)
30,New Jersey,8904413,48.773872,51.226128,67.987559,29,73014,10.835515,8.828611
6,Connecticut,3593222,48.747531,51.252469,71.639826,25,71184,10.513684,8.821887
8,District of Columbia,647484,47.363950,52.636050,74.923241,29,70848,17.999981,9.599928
20,Maryland,5930538,48.438152,51.561848,70.520432,29,69200,10.021199,7.483672
21,Massachusetts,6705586,48.461835,51.538165,72.336676,24,65974,11.609440,7.618887

##### The top 5 states based on 2015 average income result to be all on the East Coast.

In [7]:
# Top States by lowest 'Poverty Rate (%)':
top_low_pov_2015 = states_2015_stats.sort_values('Poverty Rate (%)', ascending=True)
top_low_pov_2015.head(5)

,State,State Pop,Male Pop (%),Female Pop (%),Adult Pop (%),Avg Commute (min),Avg Income,Poverty Rate (%),Unemployed (%)
29,New Hampshire,1324201,49.349306,50.650694,77.037398,24,60648,8.926968,5.751544
20,Maryland,5930538,48.438152,51.561848,70.520432,29,69200,10.021199,7.483672
1,Alaska,733375,52.382478,47.617522,71.443123,10,64197,10.173786,8.444520
6,Connecticut,3593222,48.747531,51.252469,71.639826,25,71184,10.513684,8.821887
30,New Jersey,8904413,48.773872,51.226128,67.987559,29,73014,10.835515,8.828611

##### The top 5 states based on 2015 lowest poverty rate results to be mostly on the East Coast and Alaska.

In [8]:
# Top States by lowest 'Avg Commute (min)':
top_low_commute_2015 = states_2015_stats.sort_values('Avg Commute (min)', ascending=True)
top_low_commute_2015.head(5)

,State,State Pop,Male Pop (%),Female Pop (%),Adult Pop (%),Avg Commute (min),Avg Income,Poverty Rate (%),Unemployed (%)
1,Alaska,733375,52.382478,47.617522,71.443123,10,64197,10.173786,8.444520
42,South Dakota,843190,50.223200,49.776800,73.740201,16,47356,14.135723,4.808643
26,Montana,1014699,50.277274,49.722726,76.993276,17,44497,15.199483,6.336362
27,Nebraska,1869365,49.728437,50.271563,71.353641,17,48646,12.746414,4.696301
34,North Dakota,721640,50.989829,49.010171,75.728341,17,55574,11.465689,2.911424

##### The top 5 states based on 2015 lowest average commute times in the entire country result to be the less populated and/or the smaller states.

In [9]:
# Reading our cleaned dataset '2017' and printing for preview:
states_2017 = pd.read_csv('../Output/2017_cleaned_state.csv')
states_2017.head()

,State,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,...,OtherTrans,WorkatHome,MeanCommute,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Poverty,ChildPoverty,Unemployment
0,Alabama,4850771,2350806,2499965,198385,3197877,1280323,22671,61659,926,...,20721,63042,25,1624514,320525,106343,3905,871849,1258459,366302
1,Alaska,738565,386319,352246,50301,454526,22330,101633,44754,8646,...,18812,15742,10,241717,89250,22129,709,75144,99936,59123
2,Arizona,6809946,3385055,3424891,2103443,3785517,277136,264780,208375,11879,...,76986,173850,21,2357823,411571,178504,3943,1154434,1633853,490949
3,Arkansas,2977944,1461651,1516293,213373,2174088,457312,17022,42027,6770,...,15631,41029,22,997809,198806,77564,2215,541298,769388,189390
4,California,38982847,19366579,19616268,15106298,14778217,2162560,138859,5430051,135141,...,458329,998319,25,14065256,2429116,1465746,33582,5893442,7890893,3028451

In [10]:
# Building a new dataframe to pull from and then be able to perform a summary of statistics:
sss_2017 = states_2017[['State', 'TotalPop', 'Men', 'Women', 'VotingAgeCitizen', 'MeanCommute', 'Income','Poverty', 'Unemployment']]
sss_2017.head()

,State,TotalPop,Men,Women,VotingAgeCitizen,MeanCommute,Income,Poverty,Unemployment
0,Alabama,4850771,2350806,2499965,3651914,25,40271,871849,366302
1,Alaska,738565,386319,352246,530553,10,66425,75144,59123
2,Arizona,6809946,3385055,3424891,4690177,21,45816,1154434,490949
3,Arkansas,2977944,1461651,1516293,2183895,22,39025,541298,189390
4,California,38982847,19366579,19616268,24970109,25,61046,5893442,3028451

In [11]:
# Performing calculations to pull stats:

# Calculating percentages (%) of men + women per state population:
tot_state_pop_2017 = sss_2017['TotalPop']
men_per_state_2017 = sss_2017['Men']
women_per_state_2017 = sss_2017['Women']
pct_men_2017 = (men_per_state_2017 / tot_state_pop_2017) * 100
pct_women_2017 = (women_per_state_2017 / tot_state_pop_2017) * 100

# Calculating percentage (%) of voting age citizens per state:
vot_age_2017 = sss_2017['VotingAgeCitizen']
pct_AdultsOver18_2017 = (vot_age_2017 / tot_state_pop_2017) * 100

# 'MeanCommute' will be renamed 'Average Commute Times (mins)'
# 'Income' will be renamed 'Average Income ($)'
# 'Poverty' will be renamed 'Poverty Rate (%)':
poverty_2017 = sss_2017['Poverty']
pct_pov_2017 = (poverty_2017 / tot_state_pop_2017) * 100

# Calculating percentage (%) of unemployment per state:
unemp_2017 = sss_2017['Unemployment']
pct_unemp_2017 = (unemp_2017 / tot_state_pop_2017) * 100

In [12]:
# States Summary of Statistics Table:

states_2017_stats = pd.DataFrame({
    "State": sss_2017['State'],
    "State Pop": tot_state_pop_2017,
    "Male Pop (%)": pct_men_2017,
    "Female Pop (%)": pct_women_2017,
    "Adult Pop (%)": pct_AdultsOver18_2017,
    "Avg Commute (min)": sss_2017['MeanCommute'],
    "Avg Income": sss_2017['Income'],
    "Poverty Rate (%)": pct_pov_2017,
    "Unemployed (%)": pct_unemp_2017
})
states_2017_stats.style.format({
    "State Pop": "{:,}",
    "Male Pop (%)": "{:.2f}",
    "Female Pop (%)": "{:.2f}",
    "Adult Pop (%)": "{:.2f}",
    "Avg Commute (min)": "{:.1f}",
    "Avg Income": "${:,}",
    "Poverty Rate (%)": "{:.2f}",
    "Unemployed (%)": "{:.2f}"
})

In [13]:
# Top States by 'Avg Income':
top_income_2017 = states_2017_stats.sort_values('Avg Income', ascending=False)
top_income_2017.head(5)

,State,State Pop,Male Pop (%),Female Pop (%),Adult Pop (%),Avg Commute (min),Avg Income,Poverty Rate (%),Unemployed (%)
8,District of Columbia,672391,47.449475,52.550525,74.824321,30,77649,17.399995,7.999958
30,New Jersey,8960161,48.797349,51.202651,68.551581,30,77047,10.685745,6.980600
6,Connecticut,3594478,48.798351,51.201649,72.327442,25,74496,10.075371,7.256575
20,Maryland,5996079,48.469625,51.530375,70.858006,30,72541,9.741216,6.172634
21,Massachusetts,6789319,48.508930,51.491070,72.638640,24,71030,11.132854,6.017511

##### The top 5 states based on 2017 average income result to be all on the East Coast again. It remains to be the same 5 states as in 2015 just in a slightly different rank. In 2015 the #1 state was New Jersey whereas in 2017 #1 is D.C.

In [14]:
# Top States by lowest 'Poverty Rate (%)':
top_low_pov_2017 = states_2017_stats.sort_values('Poverty Rate (%)', ascending=True)
top_low_pov_2017.head(5)

,State,State Pop,Male Pop (%),Female Pop (%),Adult Pop (%),Avg Commute (min),Avg Income,Poverty Rate (%),Unemployed (%)
29,New Hampshire,1331848,49.489957,50.510043,77.687919,25,64901,8.150930,4.485121
20,Maryland,5996079,48.469625,51.530375,70.858006,30,72541,9.741216,6.172634
6,Connecticut,3594478,48.798351,51.201649,72.327442,25,74496,10.075371,7.256575
1,Alaska,738565,52.306703,47.693297,71.835654,10,66425,10.174325,8.005118
11,Hawaii,1421658,50.221713,49.778287,71.498771,20,68663,10.350098,4.858412

##### The top 5 states based on 2017 lowest poverty rate results to be mostly on the East Coast to the exception of Alaska and Hawaii. It seems to be that Hawaii has decreased their poverty rate since 2015 and replaced New Jersey. New Jersey's poverty has increased since 2015.

In [15]:
# Top States by lowest 'Avg Commute (min)':
top_low_commute_2017 = states_2017_stats.sort_values('Avg Commute (min)', ascending=True)
top_low_commute_2017.head(5)

,State,State Pop,Male Pop (%),Female Pop (%),Adult Pop (%),Avg Commute (min),Avg Income,Poverty Rate (%),Unemployed (%)
1,Alaska,738565,52.306703,47.693297,71.835654,10,66425,10.174325,8.005118
42,South Dakota,855444,50.334914,49.665086,73.611364,16,50408,13.913477,4.021888
26,Montana,1029862,50.284407,49.715593,77.105865,17,47746,14.346194,4.902113
27,Nebraska,1893921,49.819765,50.180235,71.285814,17,51928,11.997016,3.789757
16,Kansas,2903820,49.795786,50.204214,71.262578,17,50022,12.852656,4.809871

##### The top 5 states based on 2017 lowest average commute per state don't change much from 2015 to 2017. However, Kansas just replaced North Dakota for 2017.

### Now, we can compare each state's averages/percentages to the national averages/percentages for 2015:

In [16]:
#Data collection for national stats:
total_pop = states_2015["TotalPop"].sum()
men = states_2015["Men"].sum()/total_pop * 100
women= states_2015["Women"].sum()/total_pop * 100
employed_num = states_2015["Employed"].sum()
employed = states_2015["Employed"].sum()/total_pop * 100
income_avg = states_2015["Income"].mean()
professional = states_2015["Professional"].sum()/employed_num * 100
service = states_2015["Service"].sum()/employed_num * 100
office = states_2015["Office"].sum()/employed_num * 100
construction = states_2015["Construction"].sum()/employed_num * 100
production = states_2015["Production"].sum()/employed_num * 100
drive = states_2015["Drive"].sum()/employed_num * 100
carpool = states_2015["Carpool"].sum()/employed_num * 100
transit = states_2015["Transit"].sum()/employed_num * 100
walk = states_2015["Walk"].sum()/employed_num * 100
workathome = states_2015["WorkatHome"].sum()/employed_num * 100
privatework = states_2015["PrivateWork"].sum()/employed_num * 100
publicwork = states_2015["PublicWork"].sum()/employed_num * 100
selfemployed = states_2015["SelfEmployed"].sum()/employed_num * 100
familywork = states_2015["FamilyWork"].sum()/employed_num * 100
poverty = states_2015["Poverty"].sum()/employed_num * 100
childpoverty = states_2015["ChildPoverty"].sum()/total_pop * 100
unemployment = states_2015["Unemployment"].sum()/total_pop * 100

In [17]:
national_stats_2015 = pd.DataFrame({
                           "Total Pop": [total_pop],
                           "Men": [men],
                           "Women": [women],
                           "Avg Income": [income_avg],
                           "Employed": [employed],
                           "Professional": [professional],
                           "Service": [service],
                           "Office": [office],
                           "Construction": [construction],
                           "Production": [production],
                           "Drive": [drive],
                           "Carpool": [carpool],
                           "Transit": [transit],
                           "Walk": [walk],
                           "Work at Home": [workathome],
                           "Private Work": [privatework],
                           "Public Work": [publicwork],
                           "Self Employed": [selfemployed],
                           "Family Work": [familywork],
                           "Poverty": [poverty],
                           "Child Poverty": [childpoverty],
                           "Unemployed": [unemployment]})
national_stats_2015.style.format({
                         "Total Pop":"{:,}",
                         "Men":"{:,.2f}%",
                         "Women":"{:,.2f}%",
                         "Avg Income":"${:,.2f}",
                         "Employed":"{:,.2f}%",
                         "Professional":"{:,.2f}%",
                         "Service":"{:,.2f}%",
                         "Office":"{:,.2f}%",
                         "Construction":"{:,.2f}%",
                         "Production":"{:,.2f}%",
                         "Drive":"{:,.2f}%",
                         "Carpool":"{:,.2f}%",
                         "Transit":"{:,.2f}%",
                         "Walk":"{:,.2f}%",
                         "Work at Home":"{:,.2f}%",
                         "Private Work":"{:,.2f}%",
                         "Public Work":"{:,.2f}%",
                         "Self Employed":"{:,.2f}%",
                         "Family Work":"{:,.2f}%",
                         "Poverty":"{:,.2f}%",
                         "Child Poverty":"{:,.2f}%",
                         "Unemployed":"{:,.2f}%"})

### Now, we can compare each state's averages/percentages to the national averages/percentages for 2017:

In [18]:
#Data collection for national stats:
total_pop = states_2017["TotalPop"].sum()
men = states_2017["Men"].sum()/total_pop * 100
women= states_2017["Women"].sum()/total_pop * 100
employed_num = states_2017["Employed"].sum()
employed = states_2017["Employed"].sum()/total_pop * 100
income_avg = states_2017["Income"].mean()
professional = states_2017["Professional"].sum()/employed_num * 100
service = states_2017["Service"].sum()/employed_num * 100
office = states_2017["Office"].sum()/employed_num * 100
construction = states_2017["Construction"].sum()/employed_num * 100
production = states_2017["Production"].sum()/employed_num * 100
drive = states_2017["Drive"].sum()/employed_num * 100
carpool = states_2017["Carpool"].sum()/employed_num * 100
transit = states_2017["Transit"].sum()/employed_num * 100
walk = states_2017["Walk"].sum()/employed_num * 100
workathome = states_2017["WorkatHome"].sum()/employed_num * 100
privatework = states_2017["PrivateWork"].sum()/employed_num * 100
publicwork = states_2017["PublicWork"].sum()/employed_num * 100
selfemployed = states_2017["SelfEmployed"].sum()/employed_num * 100
familywork = states_2017["FamilyWork"].sum()/employed_num * 100
poverty = states_2017["Poverty"].sum()/employed_num * 100
childpoverty = states_2017["ChildPoverty"].sum()/total_pop * 100
unemployment = states_2017["Unemployment"].sum()/total_pop * 100

In [19]:
national_stats_2017 = pd.DataFrame({
                           "Total Pop": [total_pop],
                           "Men": [men],
                           "Women": [women],
                           "Avg Income": [income_avg],
                           "Employed": [employed],
                           "Professional": [professional],
                           "Service": [service],
                           "Office": [office],
                           "Construction": [construction],
                           "Production": [production],
                           "Drive": [drive],
                           "Carpool": [carpool],
                           "Transit": [transit],
                           "Walk": [walk],
                           "Work at Home": [workathome],
                           "Private Work": [privatework],
                           "Public Work": [publicwork],
                           "Self Employed": [selfemployed],
                           "Family Work": [familywork],
                           "Poverty": [poverty],
                           "Child Poverty": [childpoverty],
                           "Unemployed": [unemployment]})
national_stats_2017.style.format({
                         "Total Pop":"{:,}",
                         "Men":"{:,.2f}%",
                         "Women":"{:,.2f}%",
                         "Avg Income":"${:,.2f}",
                         "Employed":"{:,.2f}%",
                         "Professional":"{:,.2f}%",
                         "Service":"{:,.2f}%",
                         "Office":"{:,.2f}%",
                         "Construction":"{:,.2f}%",
                         "Production":"{:,.2f}%",
                         "Drive":"{:,.2f}%",
                         "Carpool":"{:,.2f}%",
                         "Transit":"{:,.2f}%",
                         "Walk":"{:,.2f}%",
                         "Work at Home":"{:,.2f}%",
                         "Private Work":"{:,.2f}%",
                         "Public Work":"{:,.2f}%",
                         "Self Employed":"{:,.2f}%",
                         "Family Work":"{:,.2f}%",
                         "Poverty":"{:,.2f}%",
                         "Child Poverty":"{:,.2f}%",
                         "Unemployed":"{:,.2f}%"})

In [20]:
# MAYBE ADD VISUALIZATIONS HERE FOR STATE AND NATIONAL LEVEL SUMMARY ...........